// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/kv"
)

type RelationStore struct {
	AddStub        func(context.Context, string, []string) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	addReturns struct {
		result1 error
	}
	addReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	IDsStub        func(context.Context, string) ([]string, error)
	iDsMutex       sync.RWMutex
	iDsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	iDsReturns struct {
		result1 []string
		result2 error
	}
	iDsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	RelatedIDsStub        func(context.Context, string) ([]string, error)
	relatedIDsMutex       sync.RWMutex
	relatedIDsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	relatedIDsReturns struct {
		result1 []string
		result2 error
	}
	relatedIDsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	RemoveStub        func(context.Context, string, []string) error
	removeMutex       sync.RWMutex
	removeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	removeReturns struct {
		result1 error
	}
	removeReturnsOnCall map[int]struct {
		result1 error
	}
	ReplaceStub        func(context.Context, string, []string) error
	replaceMutex       sync.RWMutex
	replaceArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	replaceReturns struct {
		result1 error
	}
	replaceReturnsOnCall map[int]struct {
		result1 error
	}
	StreamIDsStub        func(context.Context, chan<- string) error
	streamIDsMutex       sync.RWMutex
	streamIDsArgsForCall []struct {
		arg1 context.Context
		arg2 chan<- string
	}
	streamIDsReturns struct {
		result1 error
	}
	streamIDsReturnsOnCall map[int]struct {
		result1 error
	}
	StreamRelatedIDsStub        func(context.Context, chan<- string) error
	streamRelatedIDsMutex       sync.RWMutex
	streamRelatedIDsArgsForCall []struct {
		arg1 context.Context
		arg2 chan<- string
	}
	streamRelatedIDsReturns struct {
		result1 error
	}
	streamRelatedIDsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RelationStore) Add(arg1 context.Context, arg2 string, arg3 []string) error {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.AddStub
	fakeReturns := fake.addReturns
	fake.recordInvocation("Add", []interface{}{arg1, arg2, arg3Copy})
	fake.addMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RelationStore) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *RelationStore) AddCalls(stub func(context.Context, string, []string) error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = stub
}

func (fake *RelationStore) AddArgsForCall(i int) (context.Context, string, []string) {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	argsForCall := fake.addArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *RelationStore) AddReturns(result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) AddReturnsOnCall(i int, result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) Delete(arg1 context.Context, arg2 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RelationStore) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *RelationStore) DeleteCalls(stub func(context.Context, string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *RelationStore) DeleteArgsForCall(i int) (context.Context, string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RelationStore) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) IDs(arg1 context.Context, arg2 string) ([]string, error) {
	fake.iDsMutex.Lock()
	ret, specificReturn := fake.iDsReturnsOnCall[len(fake.iDsArgsForCall)]
	fake.iDsArgsForCall = append(fake.iDsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IDsStub
	fakeReturns := fake.iDsReturns
	fake.recordInvocation("IDs", []interface{}{arg1, arg2})
	fake.iDsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RelationStore) IDsCallCount() int {
	fake.iDsMutex.RLock()
	defer fake.iDsMutex.RUnlock()
	return len(fake.iDsArgsForCall)
}

func (fake *RelationStore) IDsCalls(stub func(context.Context, string) ([]string, error)) {
	fake.iDsMutex.Lock()
	defer fake.iDsMutex.Unlock()
	fake.IDsStub = stub
}

func (fake *RelationStore) IDsArgsForCall(i int) (context.Context, string) {
	fake.iDsMutex.RLock()
	defer fake.iDsMutex.RUnlock()
	argsForCall := fake.iDsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RelationStore) IDsReturns(result1 []string, result2 error) {
	fake.iDsMutex.Lock()
	defer fake.iDsMutex.Unlock()
	fake.IDsStub = nil
	fake.iDsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *RelationStore) IDsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.iDsMutex.Lock()
	defer fake.iDsMutex.Unlock()
	fake.IDsStub = nil
	if fake.iDsReturnsOnCall == nil {
		fake.iDsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.iDsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *RelationStore) RelatedIDs(arg1 context.Context, arg2 string) ([]string, error) {
	fake.relatedIDsMutex.Lock()
	ret, specificReturn := fake.relatedIDsReturnsOnCall[len(fake.relatedIDsArgsForCall)]
	fake.relatedIDsArgsForCall = append(fake.relatedIDsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RelatedIDsStub
	fakeReturns := fake.relatedIDsReturns
	fake.recordInvocation("RelatedIDs", []interface{}{arg1, arg2})
	fake.relatedIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RelationStore) RelatedIDsCallCount() int {
	fake.relatedIDsMutex.RLock()
	defer fake.relatedIDsMutex.RUnlock()
	return len(fake.relatedIDsArgsForCall)
}

func (fake *RelationStore) RelatedIDsCalls(stub func(context.Context, string) ([]string, error)) {
	fake.relatedIDsMutex.Lock()
	defer fake.relatedIDsMutex.Unlock()
	fake.RelatedIDsStub = stub
}

func (fake *RelationStore) RelatedIDsArgsForCall(i int) (context.Context, string) {
	fake.relatedIDsMutex.RLock()
	defer fake.relatedIDsMutex.RUnlock()
	argsForCall := fake.relatedIDsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RelationStore) RelatedIDsReturns(result1 []string, result2 error) {
	fake.relatedIDsMutex.Lock()
	defer fake.relatedIDsMutex.Unlock()
	fake.RelatedIDsStub = nil
	fake.relatedIDsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *RelationStore) RelatedIDsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.relatedIDsMutex.Lock()
	defer fake.relatedIDsMutex.Unlock()
	fake.RelatedIDsStub = nil
	if fake.relatedIDsReturnsOnCall == nil {
		fake.relatedIDsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.relatedIDsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *RelationStore) Remove(arg1 context.Context, arg2 string, arg3 []string) error {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.removeMutex.Lock()
	ret, specificReturn := fake.removeReturnsOnCall[len(fake.removeArgsForCall)]
	fake.removeArgsForCall = append(fake.removeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.RemoveStub
	fakeReturns := fake.removeReturns
	fake.recordInvocation("Remove", []interface{}{arg1, arg2, arg3Copy})
	fake.removeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RelationStore) RemoveCallCount() int {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	return len(fake.removeArgsForCall)
}

func (fake *RelationStore) RemoveCalls(stub func(context.Context, string, []string) error) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = stub
}

func (fake *RelationStore) RemoveArgsForCall(i int) (context.Context, string, []string) {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	argsForCall := fake.removeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *RelationStore) RemoveReturns(result1 error) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = nil
	fake.removeReturns = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) RemoveReturnsOnCall(i int, result1 error) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = nil
	if fake.removeReturnsOnCall == nil {
		fake.removeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) Replace(arg1 context.Context, arg2 string, arg3 []string) error {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.replaceMutex.Lock()
	ret, specificReturn := fake.replaceReturnsOnCall[len(fake.replaceArgsForCall)]
	fake.replaceArgsForCall = append(fake.replaceArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.ReplaceStub
	fakeReturns := fake.replaceReturns
	fake.recordInvocation("Replace", []interface{}{arg1, arg2, arg3Copy})
	fake.replaceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RelationStore) ReplaceCallCount() int {
	fake.replaceMutex.RLock()
	defer fake.replaceMutex.RUnlock()
	return len(fake.replaceArgsForCall)
}

func (fake *RelationStore) ReplaceCalls(stub func(context.Context, string, []string) error) {
	fake.replaceMutex.Lock()
	defer fake.replaceMutex.Unlock()
	fake.ReplaceStub = stub
}

func (fake *RelationStore) ReplaceArgsForCall(i int) (context.Context, string, []string) {
	fake.replaceMutex.RLock()
	defer fake.replaceMutex.RUnlock()
	argsForCall := fake.replaceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *RelationStore) ReplaceReturns(result1 error) {
	fake.replaceMutex.Lock()
	defer fake.replaceMutex.Unlock()
	fake.ReplaceStub = nil
	fake.replaceReturns = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) ReplaceReturnsOnCall(i int, result1 error) {
	fake.replaceMutex.Lock()
	defer fake.replaceMutex.Unlock()
	fake.ReplaceStub = nil
	if fake.replaceReturnsOnCall == nil {
		fake.replaceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.replaceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) StreamIDs(arg1 context.Context, arg2 chan<- string) error {
	fake.streamIDsMutex.Lock()
	ret, specificReturn := fake.streamIDsReturnsOnCall[len(fake.streamIDsArgsForCall)]
	fake.streamIDsArgsForCall = append(fake.streamIDsArgsForCall, struct {
		arg1 context.Context
		arg2 chan<- string
	}{arg1, arg2})
	stub := fake.StreamIDsStub
	fakeReturns := fake.streamIDsReturns
	fake.recordInvocation("StreamIDs", []interface{}{arg1, arg2})
	fake.streamIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RelationStore) StreamIDsCallCount() int {
	fake.streamIDsMutex.RLock()
	defer fake.streamIDsMutex.RUnlock()
	return len(fake.streamIDsArgsForCall)
}

func (fake *RelationStore) StreamIDsCalls(stub func(context.Context, chan<- string) error) {
	fake.streamIDsMutex.Lock()
	defer fake.streamIDsMutex.Unlock()
	fake.StreamIDsStub = stub
}

func (fake *RelationStore) StreamIDsArgsForCall(i int) (context.Context, chan<- string) {
	fake.streamIDsMutex.RLock()
	defer fake.streamIDsMutex.RUnlock()
	argsForCall := fake.streamIDsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RelationStore) StreamIDsReturns(result1 error) {
	fake.streamIDsMutex.Lock()
	defer fake.streamIDsMutex.Unlock()
	fake.StreamIDsStub = nil
	fake.streamIDsReturns = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) StreamIDsReturnsOnCall(i int, result1 error) {
	fake.streamIDsMutex.Lock()
	defer fake.streamIDsMutex.Unlock()
	fake.StreamIDsStub = nil
	if fake.streamIDsReturnsOnCall == nil {
		fake.streamIDsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.streamIDsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) StreamRelatedIDs(arg1 context.Context, arg2 chan<- string) error {
	fake.streamRelatedIDsMutex.Lock()
	ret, specificReturn := fake.streamRelatedIDsReturnsOnCall[len(fake.streamRelatedIDsArgsForCall)]
	fake.streamRelatedIDsArgsForCall = append(fake.streamRelatedIDsArgsForCall, struct {
		arg1 context.Context
		arg2 chan<- string
	}{arg1, arg2})
	stub := fake.StreamRelatedIDsStub
	fakeReturns := fake.streamRelatedIDsReturns
	fake.recordInvocation("StreamRelatedIDs", []interface{}{arg1, arg2})
	fake.streamRelatedIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RelationStore) StreamRelatedIDsCallCount() int {
	fake.streamRelatedIDsMutex.RLock()
	defer fake.streamRelatedIDsMutex.RUnlock()
	return len(fake.streamRelatedIDsArgsForCall)
}

func (fake *RelationStore) StreamRelatedIDsCalls(stub func(context.Context, chan<- string) error) {
	fake.streamRelatedIDsMutex.Lock()
	defer fake.streamRelatedIDsMutex.Unlock()
	fake.StreamRelatedIDsStub = stub
}

func (fake *RelationStore) StreamRelatedIDsArgsForCall(i int) (context.Context, chan<- string) {
	fake.streamRelatedIDsMutex.RLock()
	defer fake.streamRelatedIDsMutex.RUnlock()
	argsForCall := fake.streamRelatedIDsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RelationStore) StreamRelatedIDsReturns(result1 error) {
	fake.streamRelatedIDsMutex.Lock()
	defer fake.streamRelatedIDsMutex.Unlock()
	fake.StreamRelatedIDsStub = nil
	fake.streamRelatedIDsReturns = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) StreamRelatedIDsReturnsOnCall(i int, result1 error) {
	fake.streamRelatedIDsMutex.Lock()
	defer fake.streamRelatedIDsMutex.Unlock()
	fake.StreamRelatedIDsStub = nil
	if fake.streamRelatedIDsReturnsOnCall == nil {
		fake.streamRelatedIDsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.streamRelatedIDsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RelationStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.iDsMutex.RLock()
	defer fake.iDsMutex.RUnlock()
	fake.relatedIDsMutex.RLock()
	defer fake.relatedIDsMutex.RUnlock()
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	fake.replaceMutex.RLock()
	defer fake.replaceMutex.RUnlock()
	fake.streamIDsMutex.RLock()
	defer fake.streamIDsMutex.RUnlock()
	fake.streamRelatedIDsMutex.RLock()
	defer fake.streamRelatedIDsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RelationStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kv.RelationStoreString = new(RelationStore)
